/**
 * Generates meaningful questions for pharmacy law flashcards and exams
 * by matching answer content to known pharmacy law topics.
 */
const fs = require('fs');

// ────────────────────────────────────────────────────────────
// Full question map: index → question text (352 cards)
// ────────────────────────────────────────────────────────────
const QUESTIONS = [
  /* 0 */ "What is the Controlled Substances Act (CSA)?",
  /* 1 */ "What agency enforces the Controlled Substances Act?",
  /* 2 */ "What are the criteria for Schedule I controlled substances?",
  /* 3 */ "What are examples of Schedule I drugs?",
  /* 4 */ "What are the criteria for Schedule II controlled substances?",
  /* 5 */ "What are examples of Schedule II drugs?",
  /* 6 */ "What are the criteria for Schedule III controlled substances?",
  /* 7 */ "What are examples of Schedule III drugs?",
  /* 8 */ "What are the criteria for Schedule IV controlled substances?",
  /* 9 */ "What are examples of Schedule IV drugs?",
  /* 10 */ "What are the criteria for Schedule V controlled substances?",
  /* 11 */ "What are examples of Schedule V drugs?",
  /* 12 */ "What is the codeine limit per 100 mL for Schedule V products?",
  /* 13 */ "What is the opium limit per 100 mL for Schedule V products?",
  /* 14 */ "What quantity rule applies to Schedule III prescriptions?",
  /* 15 */ "What quantity rule applies to Schedule II prescriptions?",
  /* 16 */ "What is the format of a DEA registration number?",
  /* 17 */ "How is a DEA registration number verified using the check digit?",
  /* 18 */ "What is DEA Form 224 used for?",
  /* 19 */ "What is DEA Form 224 (new)?",
  /* 20 */ "What is DEA Form 224a used for?",
  /* 21 */ "What is DEA Form 224b used for?",
  /* 22 */ "What is DEA Form 225 used for?",
  /* 23 */ "What is DEA Form 363 used for?",
  /* 24 */ "What is DEA Form 222 used for?",
  /* 25 */ "What replaced the triplicate DEA Form 222?",
  /* 26 */ "How many line items can appear on DEA Form 222?",
  /* 27 */ "How long must records of DEA Form 222 be kept?",
  /* 28 */ "What is the time limit to fill a DEA Form 222 order?",
  /* 29 */ "What happens if DEA Form 222 contains an error?",
  /* 30 */ "What must a pharmacist do if DEA Form 222 is lost or stolen?",
  /* 31 */ "What does a Power of Attorney (POA) allow for DEA Form 222?",
  /* 32 */ "What signatures are required to grant a DEA Power of Attorney?",
  /* 33 */ "What signatures are required to revoke a DEA Power of Attorney?",
  /* 34 */ "Can a narcotic treatment program use DEA Form 222?",
  /* 35 */ "What information must appear on a Schedule II prescription?",
  /* 36 */ "What types of signatures are valid on a controlled substance prescription?",
  /* 37 */ "Who is responsible for the validity of a controlled substance prescription?",
  /* 38 */ "What are common red flags that may indicate a fraudulent prescription?",
  /* 39 */ "How many times may a Schedule III–V prescription be refilled?",
  /* 40 */ "How long must Schedule II records be kept?",
  /* 41 */ "How long must Schedule III–V records be kept?",
  /* 42 */ "Can a hospital intern dispense controlled substances under the hospital's DEA registration?",
  /* 43 */ "What is DEA Form 510 used for?",
  /* 44 */ "How must a registrant terminate a DEA registration?",
  /* 45 */ "Are hospital medication orders considered prescriptions under federal law?",
  /* 46 */ "What is a valid prescription under federal law?",
  /* 47 */ "What prescription practices are NOT allowed under federal law?",
  /* 48 */ "What does MPJE stand for?",
  /* 49 */ "What organization administers the MPJE?",
  /* 50 */ "How many questions are on the MPJE?",
  /* 51 */ "How long is the MPJE exam?",
  /* 52 */ "What is the minimum number of questions a candidate must answer on the MPJE?",
  /* 53 */ "How is the MPJE score reported?",
  /* 54 */ "Is the MPJE a computer-adaptive test?",
  /* 55 */ "Can MPJE candidates skip or review questions?",
  /* 56 */ "How many times may a candidate attempt the MPJE per state?",
  /* 57 */ "What types of questions appear on the MPJE?",
  /* 58 */ "Are federal and state law questions mixed on the MPJE?",
  /* 59 */ "Are statutory citations tested on the MPJE?",
  /* 60 */ "What is the purpose of the MPJE?",
  /* 61 */ "Does passing the MPJE exempt a pharmacist from knowing individual state laws?",
  /* 62 */ "How many questions on the MPJE are scored?",
  /* 63 */ "How many answer choices are presented per MPJE question?",
  /* 64 */ "What is the supreme law of the United States?",
  /* 65 */ "Which constitutional clause establishes federal law as supreme?",
  /* 66 */ "What constitutional power allows states to regulate pharmacy?",
  /* 67 */ "Which amendment grants states their police powers?",
  /* 68 */ "Who creates statutory laws at the federal and state level?",
  /* 69 */ "Who creates administrative/regulatory laws?",
  /* 70 */ "Can administrative agencies create criminal penalties?",
  /* 71 */ "Can administrative agencies conduct investigations and hearings?",
  /* 72 */ "Where are federal statutes codified?",
  /* 73 */ "Where are federal regulations codified?",
  /* 74 */ "Where are Indiana state statutes codified?",
  /* 75 */ "Where are Indiana administrative regulations codified?",
  /* 76 */ "What process must agencies follow to create binding regulations?",
  /* 77 */ "Where are proposed federal regulations published?",
  /* 78 */ "Where can the public submit comments on proposed federal rules?",
  /* 79 */ "What completes the federal rulemaking process?",
  /* 80 */ "What does procedural due process protect?",
  /* 81 */ "Which constitutional amendment protects due process at the federal level?",
  /* 82 */ "Which constitutional amendment applies due process to state governments?",
  /* 83 */ "What does procedural due process require?",
  /* 84 */ "What does substantive due process protect?",
  /* 85 */ "What level of judicial scrutiny applies to laws affecting fundamental rights?",
  /* 86 */ "What rights does the First Amendment protect?",
  /* 87 */ "What was the purpose of the Declaration of Independence?",
  /* 88 */ "Is the Declaration of Independence legally binding law?",
  /* 89 */ "What pamphlet inspired the American Revolution?",
  /* 90 */ "What three rights does the Declaration of Independence identify as unalienable?",
  /* 91 */ "In what year was the U.S. Constitution written?",
  /* 92 */ "What are the first ten amendments to the Constitution called?",
  /* 93 */ "How many amendments does the U.S. Constitution have?",
  /* 94 */ "Which branch of government creates statutory law?",
  /* 95 */ "Which branch of government enforces laws?",
  /* 96 */ "Which branch of government interprets laws?",
  /* 97 */ "What is required to amend the U.S. Constitution?",
  /* 98 */ "What right does the Second Amendment protect?",
  /* 99 */ "What does the Third Amendment prohibit?",
  /* 100 */ "What does the Fourth Amendment protect against?",
  /* 101 */ "What rights does the Fifth Amendment protect?",
  /* 102 */ "What rights does the Sixth Amendment guarantee?",
  /* 103 */ "What does the Eighth Amendment prohibit?",
  /* 104 */ "What does the Ninth Amendment state?",
  /* 105 */ "What does the Tenth Amendment state?",
  /* 106 */ "What did the 13th Amendment do?",
  /* 107 */ "What did the 14th Amendment establish?",
  /* 108 */ "What did the 15th Amendment protect?",
  /* 109 */ "What did the 16th Amendment authorize?",
  /* 110 */ "What did the 17th Amendment change?",
  /* 111 */ "What did the 18th Amendment establish?",
  /* 112 */ "What did the 19th Amendment grant?",
  /* 113 */ "What did the 21st Amendment do?",
  /* 114 */ "What does the 22nd Amendment limit?",
  /* 115 */ "What does the 25th Amendment address?",
  /* 116 */ "What did the 26th Amendment establish?",
  /* 117 */ "Who is the head of the Executive Branch?",
  /* 118 */ "What is the term length for the U.S. President?",
  /* 119 */ "What are the primary powers of the President?",
  /* 120 */ "Who must confirm presidential appointments to the Supreme Court?",
  /* 121 */ "Who is the President of the Senate?",
  /* 122 */ "Who is second in line to the presidency after the Vice President?",
  /* 123 */ "Who is third in the presidential line of succession?",
  /* 124 */ "Who is fourth in the presidential line of succession?",
  /* 125 */ "How many chambers does Congress have?",
  /* 126 */ "How many members are in the U.S. Senate?",
  /* 127 */ "How long is a U.S. Senator's term?",
  /* 128 */ "How many members are in the U.S. House of Representatives?",
  /* 129 */ "How long is a U.S. House Representative's term?",
  /* 130 */ "How many House votes are needed to pass a bill?",
  /* 131 */ "How many Senate votes are needed to pass a bill?",
  /* 132 */ "Who may introduce a bill in Congress?",
  /* 133 */ "Where does a bill go after introduction in Congress?",
  /* 134 */ "What resolves differences between House and Senate versions of a bill?",
  /* 135 */ "What are the President's options when presented with a bill?",
  /* 136 */ "What vote is needed to override a presidential veto?",
  /* 137 */ "Which Article of the Constitution establishes the Judicial Branch?",
  /* 138 */ "What are the three levels of the federal court system?",
  /* 139 */ "What is the role of U.S. District Courts?",
  /* 140 */ "What cases fall under federal question jurisdiction?",
  /* 141 */ "What is diversity jurisdiction?",
  /* 142 */ "How many justices sit on the U.S. Supreme Court?",
  /* 143 */ "How long do federal judges serve?",
  /* 144 */ "What is a writ of certiorari?",
  /* 145 */ "How many cases does the Supreme Court typically hear per year?",
  /* 146 */ "What is common law?",
  /* 147 */ "What is stare decisis?",
  /* 148 */ "What is the Latin meaning of stare decisis?",
  /* 149 */ "What is the Federal Register?",
  /* 150 */ "What three criteria must a valid regulation meet?",
  /* 151 */ "What types of non-binding guidance can agencies issue?",
  /* 152 */ "What enforcement actions can agencies take?",
  /* 153 */ "Who ultimately reviews the legality of agency actions?",
  /* 154 */ "What prerequisites must be met before challenging agency action in court?",
  /* 155 */ "What department oversees the FDA?",
  /* 156 */ "Which agencies are part of HHS?",
  /* 157 */ "What does the FDA regulate?",
  /* 158 */ "What does the DEA regulate?",
  /* 159 */ "What does CMS regulate?",
  /* 160 */ "What does the FTC regulate?",
  /* 161 */ "What constitutional authority allows Congress to regulate drugs nationally?",
  /* 162 */ "Who has authority over interstate drug commerce?",
  /* 163 */ "Who has authority over intrastate drug commerce?",
  /* 164 */ "What do statutes typically provide regarding agency authority?",
  /* 165 */ "What do regulations provide that statutes do not?",
  /* 166 */ "What is a more formal legal authority than a regulation?",
  /* 167 */ "What is the United States Code (USC)?",
  /* 168 */ "How many titles does the United States Code have?",
  /* 169 */ "Which USC title covers food and drugs?",
  /* 170 */ "What does the title number represent in USC citations?",
  /* 171 */ "What does 'section' refer to in a USC citation?",
  /* 172 */ "What does 'paragraph' refer to in a USC citation?",
  /* 173 */ "What is the Code of Federal Regulations (CFR)?",
  /* 174 */ "How many titles does the CFR have?",
  /* 175 */ "What does Title 21 of the CFR cover?",
  /* 176 */ "What does the part number represent in a CFR citation?",
  /* 177 */ "What does the section number represent in a CFR citation?",
  /* 178 */ "Where are new federal rules published before entering the CFR?",
  /* 179 */ "What is the Indiana Code?",
  /* 180 */ "What is the Indiana Administrative Code?",
  /* 181 */ "What does 'title' refer to in the Indiana Code?",
  /* 182 */ "What title of the Indiana Administrative Code governs the Board of Pharmacy?",
  /* 183 */ "Who administers pharmacy law in Indiana?",
  /* 184 */ "Where are proposed Indiana rules published?",
  /* 185 */ "What gives Indiana agencies the authority to create regulations?",
  /* 186 */ "Can Indiana's Board of Pharmacy create criminal laws?",
  /* 187 */ "What are the requirements for a valid Indiana administrative regulation?",
  /* 188 */ "Who regulates interstate controlled substance commerce?",
  /* 189 */ "Who regulates intrastate controlled substance matters under police powers?",
  /* 190 */ "Who grants DEA registration?",
  /* 191 */ "Where are proposed Indiana rules published before becoming final?",
  /* 192 */ "Where must Indiana rules appear to be effective?",
  /* 193 */ "Who may comment on proposed Indiana administrative rules?",
  /* 194 */ "Where can the public find proposed Indiana rules online?",
  /* 195 */ "What is an ANPR (Advance Notice of Proposed Rulemaking)?",
  /* 196 */ "What is an NPRM (Notice of Proposed Rulemaking)?",
  /* 197 */ "What is the final step in completing the rulemaking process?",
  /* 198 */ "Once finalized, where are federal regulations permanently codified?",
  /* 199 */ "Can Congress overturn a final agency rule?",
  /* 200 */ "Under what circumstances can a court overturn an agency rule?",
  /* 201 */ "What is an Administrative Law Judge (ALJ)?",
  /* 202 */ "What is an Administrative Order?",
  /* 203 */ "What is judicial review in the context of administrative law?",
  /* 204 */ "What does an authorization bill do?",
  /* 205 */ "What does an appropriations bill do?",
  /* 206 */ "Can a program operate without an appropriations bill?",
  /* 207 */ "Which congressional committees handle Medicare and Medicaid legislation?",
  /* 208 */ "What does HELP stand for in Senate committee names?",
  /* 209 */ "What three questions guide judicial review of agency actions?",
  /* 210 */ "What are the two types of due process?",
  /* 211 */ "What makes a controlled substance prescription valid under federal law?",
  /* 212 */ "Who is responsible for verifying a controlled substance prescription?",
  /* 213 */ "What federal form or system is used to order Schedule I and II drugs?",
  /* 214 */ "How often must DEA registrants reinspect their controlled substance records?",
  /* 215 */ "How must Schedule II controlled substance records be stored?",
  /* 216 */ "What quantity may be dispensed in an emergency oral Schedule II order?",
  /* 217 */ "Why do states require controlled substance reporting to a prescription monitoring program?",
  /* 218 */ "Who may access a state prescription drug monitoring program (PDMP)?",
  /* 219 */ "How many times may a Schedule III or IV prescription be refilled?",
  /* 220 */ "May a Schedule II prescription be refilled?",
  /* 221 */ "How many times may a Schedule V prescription be refilled?",
  /* 222 */ "When may a pharmacy transfer controlled substance inventory?",
  /* 223 */ "What are USP chapters <795> and <797>?",
  /* 224 */ "What is the purpose of USP chapter <800>?",
  /* 225 */ "What controls are required under USP <800>?",
  /* 226 */ "What is pharmacy malpractice?",
  /* 227 */ "What are the four elements of negligence?",
  /* 228 */ "What is vicarious liability?",
  /* 229 */ "What is strict liability in products liability?",
  /* 230 */ "What does PHI stand for?",
  /* 231 */ "What two HIPAA rules protect health information?",
  /* 232 */ "Under HIPAA, when may PHI be disclosed without patient authorization?",
  /* 233 */ "What does a DEA inspection of a pharmacy typically cover?",
  /* 234 */ "What is the role of an Administrative Law Judge in agency hearings?",
  /* 235 */ "What is an administrative final order?",
  /* 236 */ "What is a 'scope of practice' for healthcare professionals?",
  /* 237 */ "May pharmacists prescribe medications in all states?",
  /* 238 */ "What determines a pharmacist's scope of practice?",
  /* 239 */ "What are a pharmacy's general legal obligations?",
  /* 240 */ "What must a pharmacy do if controlled substances are stolen or significantly lost?",
  /* 241 */ "What is an adulterated drug?",
  /* 242 */ "What is a misbranded drug?",
  /* 243 */ "What is a pocket veto?",
  /* 244 */ "What is a Conference Committee?",
  /* 245 */ "What is therapeutic substitution?",
  /* 246 */ "What is generic substitution?",
  /* 247 */ "What federal law governs product misuse vs. intended use?",
  /* 248 */ "What was the primary purpose of the Federal Food, Drug, and Cosmetic Act of 1938?",
  /* 249 */ "Was the FDCA of 1938 primarily triggered by an efficacy failure?",
  /* 250 */ "Which agency enforces the Federal Food, Drug, and Cosmetic Act?",
  /* 251 */ "What disaster led to the Federal Food, Drug, and Cosmetic Act of 1938?",
  /* 252 */ "What new requirement did the FD&C Act of 1938 introduce for drugs?",
  /* 253 */ "What authority did the 1938 FD&C Act give the FDA over manufacturers?",
  /* 254 */ "What additional product categories did the 1938 FD&C Act add to FDA oversight?",
  /* 255 */ "What major distinction did the Durham-Humphrey Amendment of 1951 create?",
  /* 256 */ "What label was required under the Durham-Humphrey Amendment for Rx-only drugs?",
  /* 257 */ "Under the Durham-Humphrey Amendment, could Rx drugs be refilled?",
  /* 258 */ "What tragedy prompted the Kefauver-Harris Amendment of 1962?",
  /* 259 */ "What new requirement did the Kefauver-Harris Amendment of 1962 add?",
  /* 260 */ "What type of clinical trials must support drug efficacy under the Kefauver-Harris Amendment?",
  /* 261 */ "What patient protection did the Kefauver-Harris Amendment add to clinical trials?",
  /* 262 */ "What manufacturing standards did the Kefauver-Harris Amendment require?",
  /* 263 */ "Did the Kefauver-Harris Amendment require retroactive efficacy review of older drugs?",
  /* 264 */ "What scheduling system did the Comprehensive Drug Abuse Prevention and Control Act of 1970 create?",
  /* 265 */ "What criteria determine a drug's DEA schedule?",
  /* 266 */ "Which agency shares responsibility for scheduling decisions with HHS?",
  /* 267 */ "What amendment of 1962 established efficacy requirements for drug approval?",
  /* 268 */ "What federal law allows generic drugs to be approved more easily?",
  /* 269 */ "What application process did Hatch-Waxman create for generics?",
  /* 270 */ "What must a generic drug manufacturer demonstrate instead of full clinical trials?",
  /* 271 */ "What balance did the Hatch-Waxman Act seek to achieve?",
  /* 272 */ "What law requires child-resistant packaging for most medications?",
  /* 273 */ "Can seniors request non-child-resistant packaging?",
  /* 274 */ "What did OBRA '90 require pharmacies to perform before dispensing to Medicaid patients?",
  /* 275 */ "What patient counseling obligation did OBRA '90 create?",
  /* 276 */ "Did states extend OBRA '90 counseling requirements beyond Medicaid?",
  /* 277 */ "What system did the Drug Supply Chain Security Act (DSCSA) create?",
  /* 278 */ "What three data elements must be tracked under DSCSA?",
  /* 279 */ "What does the FDA Modernization Act of 1997 permit regarding off-label information?",
  /* 280 */ "What does REMS stand for?",
  /* 281 */ "Did the FDA Amendments Act of 2007 give the FDA authority to require REMS?",
  /* 282 */ "How does the FDA detect illegal drug promotion?",
  /* 283 */ "When is a dietary supplement considered a drug under the FDCA?",
  /* 284 */ "When can a product be both a cosmetic and a drug?",
  /* 285 */ "Can a product be classified as both food and drug under the FDCA?",
  /* 286 */ "Is Medicare eligibility based on income?",
  /* 287 */ "What are the four parts of Medicare?",
  /* 288 */ "What is the monthly cap for insulin under Medicare Part D?",
  /* 289 */ "What is the annual out-of-pocket cap under the Inflation Reduction Act for Medicare Part D?",
  /* 290 */ "Which drug classes are protected under Medicare Part D and must be covered by all plans?",
  /* 291 */ "What is the 'any willing provider' rule in Medicare Part D?",
  /* 292 */ "What is the penalty period for late Medicare Part D enrollment?",
  /* 293 */ "What is the late enrollment penalty for Medicare Part D?",
  /* 294 */ "What is the Low-Income Subsidy (LIS/Extra Help) under Medicare Part D?",
  /* 295 */ "What are the three largest pharmacy benefit managers (PBMs) in the U.S.?",
  /* 296 */ "What is the difference between an HMO and a PPO?",
  /* 297 */ "What does the Anti-Kickback Statute prohibit?",
  /* 298 */ "Does the Anti-Kickback Statute apply to Medicare and Medicaid?",
  /* 299 */ "Are pharmacy discount cards considered kickbacks under the Anti-Kickback Statute?",
  /* 300 */ "Who enforces the Anti-Kickback Statute?",
  /* 301 */ "What are 'safe harbors' under the Anti-Kickback Statute?",
  /* 302 */ "What does the Stark Law (Physician Self-Referral Law) prohibit?",
  /* 303 */ "Does the Stark Law apply to pharmacies?",
  /* 304 */ "What are 'designated health services' under the Stark Law?",
  /* 305 */ "What does the False Claims Act (FCA) prohibit?",
  /* 306 */ "What penalties can a violator face under the False Claims Act?",
  /* 307 */ "What is a 'qui tam' lawsuit?",
  /* 308 */ "What did OBRA '90 require of pharmacies as a condition of Medicaid participation?",
  /* 309 */ "What does a Drug Utilization Review (DUR) screen for?",
  /* 310 */ "What are the three main provisions of OBRA '90?",
  /* 311 */ "What exactly did OBRA '90 require regarding patient counseling?",
  /* 312 */ "Can patients refuse pharmacist counseling?",
  /* 313 */ "What information must be collected as part of a patient medication profile?",
  /* 314 */ "In what year was HIPAA enacted?",
  /* 315 */ "What qualifies as Protected Health Information (PHI) under HIPAA?",
  /* 316 */ "What is the 'minimum necessary' standard under HIPAA?",
  /* 317 */ "Who are 'covered entities' under HIPAA?",
  /* 318 */ "Which HHS office enforces HIPAA?",
  /* 319 */ "How long must HIPAA records and policies be retained?",
  /* 320 */ "What must a covered entity do after a major HIPAA breach?",
  /* 321 */ "Are business associates (e.g., PBMs) required to comply with HIPAA?",
  /* 322 */ "What does HIPAA allow regarding refill reminder calls?",
  /* 323 */ "How is Medicaid funded?",
  /* 324 */ "Is Medicaid expansion optional for states?",
  /* 325 */ "What is a 'dual eligible' patient?",
  /* 326 */ "Can a dual-eligible patient use both Medicare Part D and Medicaid for the same drug?",
  /* 327 */ "Does Indiana have a Medicaid program?",
  /* 328 */ "Must Indiana Medicaid cover FDA-approved drugs?",
  /* 329 */ "Who is eligible for Medicare?",
  /* 330 */ "Do private insurers generally follow Medicare coverage guidelines?",
  /* 331 */ "What are the phases of Medicare Part D coverage?",
  /* 332 */ "What is the coinsurance in the Medicare Part D catastrophic phase?",
  /* 333 */ "Who pays in the Medicare Part D coverage gap (donut hole)?",
  /* 334 */ "Who pays in the Medicare Part D catastrophic coverage phase?",
  /* 335 */ "What is Medication Therapy Management (MTM)?",
  /* 336 */ "What three core elements must MTM include?",
  /* 337 */ "What vaccines does Medicare Part D cover?",
  /* 338 */ "Which drugs are excluded from Medicare Part D coverage?",
  /* 339 */ "What are the Medicaid programs in Indiana?",
  /* 340 */ "Who is eligible for Indiana Hoosier Healthwise?",
  /* 341 */ "Who is eligible for Indiana Healthy Indiana Plan (HIP)?",
  /* 342 */ "Who is eligible for Indiana Traditional Medicaid (elderly/disabled)?",
  /* 343 */ "What does a pharmacist's DUR process check for?",
  /* 344 */ "What must be documented during a pharmacist-patient DUR interaction?",
  /* 345 */ "What are the four HIPAA standards?",
  /* 346 */ "Who are HIPAA covered entities?",
  /* 347 */ "Can a pharmacy leave a prescription at a pickup counter without violating HIPAA?",
  /* 348 */ "What are HIPAA Security Rule safeguards?",
  /* 349 */ "What are examples of PHI identifiers under HIPAA?",
  /* 350 */ "What must a pharmacy do before sharing PHI with a patient's family member?",
  /* 351 */ "What is the timeframe for notifying individuals of a HIPAA breach?",
];

// ────────────────────────────────────────────────────────────
// Apply questions to lawData.js
// ────────────────────────────────────────────────────────────
let code = fs.readFileSync('src/lawData.js', 'utf8');

// ── 1. Replace flashcard q fields ──
// Format: "id": "law_fc_N",\n        "q": "Question N+1",  (8 spaces)
for (let i = 0; i < QUESTIONS.length; i++) {
  const escaped = QUESTIONS[i].replace(/"/g, '\\"');
  const oldQ = `"id": "law_fc_${i}",\n        "q": "Question ${i + 1}",`;
  const newQ = `"id": "law_fc_${i}",\n        "q": "${escaped}",`;
  if (code.includes(oldQ)) {
    code = code.replace(oldQ, newQ);
  } else {
    console.warn(`FC pattern not found for index ${i}`);
  }
}

// ── 2. Replace exam q fields ──
// Format: "id": "law_ex_N",\n        "q": "What is a key point...",  (8 spaces)
for (let i = 0; i < QUESTIONS.length; i++) {
  const escaped = QUESTIONS[i].replace(/"/g, '\\"');
  const oldQ = `"id": "law_ex_${i}",\n        "q": "What is a key point regarding this item?",`;
  const newQ = `"id": "law_ex_${i}",\n        "q": "${escaped}",`;
  if (code.includes(oldQ)) {
    code = code.replace(oldQ, newQ);
  } else {
    console.warn(`EX pattern not found for index ${i}`);
  }
}

fs.writeFileSync('src/lawData.js', code);
console.log('Done! Questions applied to', QUESTIONS.length, 'cards + exams.');

// Verify first few
try {
  const {lawFlashcards, lawExams} = require('./src/lawData.js');
  console.log('FC[0].q:', lawFlashcards[0].cards[0].q);
  console.log('FC[2].q:', lawFlashcards[0].cards[2].q);
  console.log('EX[0].q:', lawExams[0].questions[0].q);
} catch(e) { console.log('Verify error:', e.message); }
